# //Soda database migration connection
development:
  dialect: postgres
  database: f2xhotel
  user: postgres
  password: postgres
  host: localhost
  pool: 5

test:
  url: {{envOr "TEST_DATABASE_URL" "postgres://postgres:postgres@localhost:5432/myapp_test"}}

production:
  url: {{envOr "DATABASE_URL" "postgres://postgres:postgres@localhost:5432/myapp_production"}}