version: '3.9'
services:
  f2xhotel:
    build: .
    ports:
      - 8080:8080
    
    volumes:
      - .:/app
    depends_on:
      # -   db_mysql
      -   db_postgres
  

  # Database service 

  # # Mysql
  # db_mysql:
  #   image: mysql:5.7.22
  #   restart: always
  #   environment: 
  #     MYSQL_DATABASE: go_f2hotel
  #     MYSQL_USER: root
  #     MYSQL_PASSWORD: root
  #     MYSQL_ROOT_PASSWORD: root
  #   volumes:
  #     - .db_data:/var/lib/mysql
  #   ports:
  #     - 33306:3306
    

  # Postgres
  db_postgres:
    image: postgres:latest
    restart: always
    environment: 
      POSTGRES_DATABSE: f2xhotel
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGTRES_ROOT_PASSWORD: 
    volumes:
      - .db_data:/var/lib/postgres
    ports:
      - 5432:5432
  
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=psinthorn@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=adminx
    ports:
      - 5050:80
    restart: always
    volumes:
      - pgadmin:/root/.pgadmin
volumes:
  .db_data:
  pgadmin:
      
    